SELECT FOOD_PRODUCT.PRODUCT_ID
     , FOOD_PRODUCT.PRODUCT_NAME
     , SUM(FOOD_ORDER.AMOUNT * FOOD_PRODUCT.PRICE) AS TOTAL_SALES
FROM FOOD_ORDER
    LEFT JOIN FOOD_PRODUCT
    ON FOOD_ORDER.PRODUCT_ID = FOOD_PRODUCT.PRODUCT_ID
WHERE DATE_FORMAT(FOOD_ORDER.PRODUCE_DATE, "%m") = "05"
GROUP BY FOOD_PRODUCT.PRODUCT_ID, FOOD_PRODUCT.PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, FOOD_PRODUCT.PRODUCT_ID ASC