/*
USER_INFO 테이블과 ONLINE_SALE 
2021년에 가입한 전체 회원들
상품을 구매한 회원수와 상품을 구매한 회원의 비율(=2021년에 가입한 회원 중 상품을 구매한 회원수 / 2021년에 가입한 전체 회원 수)
년, 월 별로 출력
상품을 구매한 회원의 비율은 소수점 두번째자리에서 반올림
전체 결과는 년을 기준으로 오름차순 , 월을 기준으로 오름차순 정렬
*/

SELECT DATE_FORMAT(ONLINE_SALE.SALES_DATE, "%Y") AS YEAR
     , DATE_FORMAT(ONLINE_SALE.SALES_DATE, "%m") AS MONTH
     , COUNT(DISTINCT ONLINE_SALE.USER_ID) AS PUCHASED_USERS
     , ROUND(COUNT(DISTINCT ONLINE_SALE.USER_ID) / (SELECT COUNT(*) FROM USER_INFO WHERE YEAR(JOINED)="2021"), 1) AS PUCHASED_RATIO
FROM ONLINE_SALE
    LEFT JOIN USER_INFO ON ONLINE_SALE.USER_ID = USER_INFO.USER_ID
WHERE YEAR(USER_INFO.JOINED) ="2021" 
GROUP BY YEAR, MONTH
ORDER BY 1,2