# PRODUCT 테이블과 OFFLINE_SALE 테이블
# 상품코드 별 매출액(판매가 * 판매량) 합계를 출력하는 SQL문을 작성
# 결과는 매출액을 기준으로 내림차순 정렬, 매출액이 같다면 상품코드를 기준으로 오름차순 정렬

SELECT PRODUCT.PRODUCT_CODE
     , SUM(PRODUCT.PRICE*SALE.SALES_AMOUNT) AS SALES
FROM OFFLINE_SALE AS SALE
    LEFT JOIN PRODUCT ON SALE.PRODUCT_ID=PRODUCT.PRODUCT_ID
GROUP BY PRODUCT.PRODUCT_CODE
ORDER BY SALES DESC, PRODUCT.PRODUCT_CODE ASC
