# 2022년 4월 13일 취소되지 않은 흉부외과(CS) 진료 예약 내역을 조회
# 진료예약번호, 환자이름, 환자번호, 진료과코드, 의사이름, 진료예약일시 항목이 출력
# 결과는 진료예약일시를 기준으로 오름차순 정렬

SELECT APPOINTMENT.APNT_NO
     , PATIENT.PT_NAME
     , PATIENT.PT_NO
     , DOCTOR.MCDP_CD
     , DOCTOR.DR_NAME
     , APPOINTMENT.APNT_YMD
FROM APPOINTMENT
    LEFT JOIN PATIENT ON APPOINTMENT.PT_NO = PATIENT.PT_NO
    LEFT JOIN DOCTOR ON APPOINTMENT.MDDR_ID=DOCTOR.DR_ID
WHERE DATE_FORMAT(APPOINTMENT.APNT_YMD, "%Y-%m-%d") = "2022-04-13" AND APPOINTMENT.APNT_CNCL_YN = "N"
ORDER BY APPOINTMENT.APNT_YMD ASC;