SELECT CONCAT("/home/grep/src/", file.BOARD_ID, "/", file.FILE_ID, file.FILE_NAME, file.FILE_EXT) AS FILE_PATH
FROM USED_GOODS_BOARD board
    LEFT JOIN USED_GOODS_FILE file ON board.BOARD_ID=file.BOARD_ID
WHERE board.VIEWS = (SELECT MAX(VIEWS) FROM USED_GOODS_BOARD)
ORDER BY file.FILE_ID DESC