# USED_GOODS_BOARD와 USED_GOODS_REPLY 테이블
# 2022년 10월에 작성된 게시글 제목, 게시글 ID, 댓글 ID, 댓글 작성자 ID, 댓글 내용, 댓글 작성일을 조회
# 결과는 댓글 작성일을 기준으로 오름차순 정렬, 댓글 작성일이 같다면 게시글 제목을 기준으로 오름차순 정렬
SELECT BOARD.TITLE
     , BOARD.BOARD_ID
     , REPLY.REPLY_id
     , REPLY.WRITER_ID
     , REPLY.CONTENTS
     , DATE_FORMAT(REPLY.CREATED_DATE, "%Y-%m-%d") AS CREATED_DATE
FROM USED_GOODS_BOARD AS BOARD
    INNER JOIN USED_GOODS_REPLY AS REPLY ON BOARD.BOARD_ID=REPLY.BOARD_ID
WHERE DATE_FORMAT(BOARD.CREATED_DATE, "%Y-%m")="2022-10"
ORDER BY REPLY.CREATED_DATE ASC, BOARD.TITLE ASC
