SELECT BOOK.CATEGORY
     , SUM(sales.SALES) AS TOTAL_SALES
FROM BOOK_SALES sales
    LEFT JOIN BOOK ON sales.BOOK_ID=BOOK.BOOK_ID
WHERE sales.SALES_DATE BETWEEN "2022-01-01" AND "2022-01-31"
GROUP BY BOOK.CATEGORY
ORDER BY CATEGORY ASC;