WITH max_price AS 
    (SELECT CATEGORY
         , MAX(PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT
    WHERE CATEGORY = "과자" OR CATEGORY = "국" OR CATEGORY = "김치" OR CATEGORY = "식용유"
    GROUP BY CATEGORY)

SELECT m.CATEGORY
     , m.MAX_PRICE
     , p.PRODUCT_NAME
FROM max_price m
 INNER JOIN FOOD_PRODUCT p ON m.category=p.category AND m.MAX_PRICE=p.PRICE
ORDER BY MAX_PRICE DESC