SELECT user.USER_ID
     , user.NICKNAME
     , SUM(board.PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD board
    LEFT JOIN USED_GOODS_USER user ON board.WRITER_ID=user.USER_ID
WHERE board.STATUS="DONE"
GROUP BY user.USER_ID
HAVING SUM(board.PRICE) >= 700000
ORDER BY SUM(board.PRICE) ASC;