# 2022년 1월의 도서 판매 데이터를 기준
# 저자 별, 카테고리 별 매출액(TOTAL_SALES = 판매량 * 판매가) 을 구하여, 
# 저자 ID(AUTHOR_ID), 저자명(AUTHOR_NAME), 카테고리(CATEGORY), 매출액(SALES) 리스트를 출력
# 결과는 저자 ID를 오름차순, 저자 ID가 같다면 카테고리를 내림차순 정렬

SELECT AUTHOR.AUTHOR_ID
     , AUTHOR.AUTHOR_NAME
     , BOOK.CATEGORY
     , SUM(BOOK_SALES.SALES)*BOOK.PRICE AS TOTAL_SALES
FROM BOOK_SALES
    LEFT JOIN BOOK ON BOOK_SALES.BOOK_ID = BOOK.BOOK_ID
    LEFT JOIN AUTHOR ON BOOK.AUTHOR_ID = AUTHOR.AUTHOR_ID
WHERE DATE_FORMAT(BOOK_SALES.sales_date, "%Y-%m-%d") BETWEEN "2022-01-01" AND "2022-01-31"
GROUP BY AUTHOR.AUTHOR_ID
       , AUTHOR.AUTHOR_NAME
       , BOOK.CATEGORY
ORDER BY AUTHOR.AUTHOR_ID ASC
       , BOOK.CATEGORY DESC