WITH max_fav AS (
    SELECT FOOD_TYPE      
         , MAX(FAVORITES) AS FAVORITES
    FROM REST_INFO
    GROUP BY FOOD_TYPE)

SELECT m.FOOD_TYPE
     , r.REST_ID
     , r.REST_NAME
     , m.FAVORITES
FROM max_fav m
    LEFT JOIN REST_INFO r ON m.FOOD_TYPE=r.FOOD_TYPE AND m.FAVORITES=r.FAVORITES
ORDER BY FOOD_TYPE DESC